### ISSUE TITLE
What exactly can you do with this?

### ISSUE THREAD

**Issue by tobimensch** [pelya/pulseaudio-android#5]
This project lacks a few more descriptive infos. What is it for? How can it be installed on my phone?

Would it be possible to provide prebuilt APKs?

**Comment by pelya** [comment]
This is for streaming audio from your Linux PC to your phone (or from your Linux chroot on your phone). It is bundled with XSDL X server, and currently won't work without XSDL. You can grab .apk file here: https://sourceforge.net/projects/libsdl-android/files/apk/XServer-XSDL/

**Comment by tobimensch** [comment]
It would great if this was working without XSDL. I think this is can be very useful. Thanks for the work.

**Comment by tobimensch** [comment]
I looked into XSDL now, and I see no information how to setup pulseaudio for this to work. Making it work together with an on the phone chroot environment is particularly interesting to me.

**Comment by pelya** [comment]
XSDL will print instructions when you launch it. You need to set env
variable PULSE_SERVER=tcp:<your-phone-IP-address>:4712 on your Linux PC or
inside chroot.

**Comment by pelya** [comment]
You can also launch XSDL via Android intent, with predefined X display
number, if you want to use it from inside chroot launcher, here's a sample
code: https://github.com/pelya/xsdl-launcher-example

**Comment by xavier83** [comment]
Is XSDL a hard dependency for this port? If it is just to get the pulseaudio sink to work on android, would this [OpenSL](https://github.com/glance-/pulseaudio-android-ndk/blob/master/pulseaudio-patches/0003-WIP-opensl-sink.patch) patch help avoid that dependency?

**Comment by pelya** [comment]
Yes, currently XSDL is required. I am going to switch to OpenSL eventually.
I've seen this patch before, it does not work.

**Comment by xavier83** [comment]
Thanks. Looking forward to it :smile:

**Comment by avodonosov** [comment]
@pelya, it would also be great if the project allowed to stream sound from android to my linux server (where my applifier is connected)

**Comment by pelya** [comment]
You cannot capture audio output on Android, so it's not possible

**Comment by avodonosov** [comment]
@pelya , not even on Linux level? A driver? A virtual headset?

**Comment by pelya** [comment]
Some manufacturers would allow capturing internal audio on Android, and anything is possible with root, but currently your best option is to put volume level to maximum and  capture microphone input in a quiet room.
