### ISSUE TITLE
Have working OpenSL ES driver

### ISSUE THREAD

**Issue by twaik** [pelya/pulseaudio-android#7]
How I can contact you to test and improve it? And then to integrate it to your code base?

**Comment by pelya** [comment]
There is nothing to test yet, the SLES plugin is not implemented.
Here's a sample SLES output plugin, from VLC project:
https://github.com/videolan/vlc/blob/master/modules/audio_output/opensles_android.c

**Comment by twaik** [comment]
I didn't mean [this one](https://github.com/pelya/pulseaudio-android/commit/f5bebe88cb4101b842b44183c7eb46aa9405eb9f). I meant [that](https://gist.github.com/twaik/0eaee765c712ddd03fc9dc4eaac09cfc). It works, but I need more tests on different devices to improve it. I though you can help me with that.

**Comment by twaik** [comment]
If it wont work or for some reasons it can not be integrated into your repo the [pipe reader](https://gist.github.com/twaik/2c766116950e668989f3497a03b29862) can be useful.

**Comment by pelya** [comment]
Oh, so you have created your own plugin, cool.
I can't help much with testing, I've kind of abandoned that project, also
it won't compile anymore with the latest Android NDK.
If you'll make a pull request I'll merge it. Or you can just fork the whole
repository and do your changes there.

**Comment by twaik** [comment]
OK, I got it. Unfortunantely I can't merge the incomplete plugin with such a project, my conscience can't let me do that :) . I posted another comment [here](https://github.com/termux/termux-packages/issues/821#issuecomment-349009168), maybe they can help me. Despite everything thank you :)

**Comment by pelya** [comment]
It's working now. You can use XSDL app from Play Store for a ready-to-use PulseAudio server on your phone.
